version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=GainVentures2025!
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://gain-ventures-n8n.onrender.com/
      - N8N_EDITOR_BASE_URL=https://gain-ventures-n8n.onrender.com/
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
